---
- name: install ubuntu-drivers-common.
  import_tasks: install-ubuntu-drivers-common.yaml
  tags: install-ubuntu-drivers-common
  when: ansible_os_family == "Debian"

- name: install recommended driver
  import_tasks: install_recommended_driver.yaml
  tags: install-recommended-driver
  when: ansible_os_family == "Debian"

- name: reboot machine.
  import_tasks: reboot_machine.yaml
  tags: reboot-machine
  when: ansible_os_family == "Debian"