---
- name: reboot machine
  reboot:
   reboot_timeout: 600
   test_command: whoami

- name: Confirm server is back online.
  command: uptime
  register: server_uptime
  when: ansible_facts['rebooted'] is defined

- name: Show Uptime stdout.
  debug:
   msg: "Server uptime: {{ server_uptime.stdout }}"
  when: not server_uptime.skipped

  



